const fetch = require('node-fetch')
let handler = async (m, { conn, args, text, usedPrefix, command  }) => {
switch (command) {
case 'aesthetic': case 'ahegao': case 'akira': case 'akiyama': case 'ana': case 'anjing': case 'art': case 'ass': case 'asuna': case 'ayuzawa': case 'bdsm': case 'boneka': case 'boruto': case 'bts': case 'cecan': case 'chiho': case 'chitoge': case 'cogan': case 'cosplay': case 'cosplayloli': case 'cosplaysagiri': case 'cuckold': case 'cum': case 'cyber': case 'darkjokes': case 'deidara': case 'doraemon': case 'eba': case 'elaina': case 'emilia': case 'ero': case 'erza': case 'exo': case 'femdom': case 'foot': case 'freefire': case 'gamewallpaper': case 'gangbang': case 'gifs': case 'glasses': case 'gremory': case 'hekel': case 'hestia': case 'hijaber': case 'hinata': case 'husbu': case 'inori': case 'islamic': case 'isuzu': case 'itachi': case 'itori': case 'jahy': case 'jeni': case 'jiso': case 'justina': case 'kaga': case 'kagura': case 'kakasih': case 'kaori': case 'kartun': case 'katakata': case 'keneki': case 'kotori': case 'kpop': case 'kucing': case 'kurumi': case 'lisa': case 'loli': case 'madara': case 'masturbation': case 'megumin': case 'mikasa': case 'mikey': case 'miku': case 'milf': case 'minato': case 'mobil': case 'motor': case 'mountain': case 'naruto': case 'neko': case 'neko2': case 'nekonime': case 'nezuko': case 'onepiece': case 'orgy': case 'panties': case 'pentol': case 'pokemon': case 'profil': case 'programming': case 'pubg': case 'pussy': case 'randblackpink': case 'randomnime': case 'randomnime2': case 'rize': case 'rose': case 'ryujin': case 'sagiri': case 'sakura': case 'sasuke': case 'satanic': case 'shina': case 'shinka': case 'shinomiya': case 'shizuka': case 'shota': case 'tatasurya': case 'technology': case 'tejina': case 'tentacles': case 'thighs': case 'toukachan': case 'tsunade': case 'waifu': case 'wallhp': case 'wallml': case 'wallnime': case 'yotsuba': case 'yuki': case 'yulibocil': case 'yumeko':{
let link
if (/aesthetic/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/aesthetic.json')).json()
if (/ahegao/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/ahegao.json')).json()
if (/akira/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/akira.json')).json()
if (/akiyama/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/akiyama.json')).json()
if (/ana/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/ana.json')).json()
if (/anjing/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/anjing.json')).json()
if (/art/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/art.json')).json()
if (/ass/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/ass.json')).json()
if (/asuna/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/asuna.json')).json()
if (/ayuzawa/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/ayuzawa.json')).json()
if (/bdsm/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/bdsm.json')).json()
if (/boneka/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/boneka.json')).json()
if (/boruto/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/boruto.json')).json()
if (/bts/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/bts.json')).json()
if (/cecan/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cecan.json')).json()
if (/chiho/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/chiho.json')).json()
if (/chitoge/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/chitoge.json')).json()
if (/cogan/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cogan.json')).json()
if (/cosplay/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cosplay.json')).json()
if (/cosplayloli/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cosplayloli.json')).json()
if (/cosplaysagiri/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cosplaysagiri.json')).json()
if (/cuckold/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cuckold.json')).json()
if (/cum/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cum.json')).json()
if (/cyber/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/cyber.json')).json()
if (/darkjokes/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/darkjokes.json')).json()
if (/deidara/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/deidara.json')).json()
if (/doraemon/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/doraemon.json')).json()
if (/eba/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/eba.json')).json()
if (/elaina/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/elaina.json')).json()
if (/emilia/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/emilia.json')).json()
if (/ero/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/ero.json')).json()
if (/erza/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/erza.json')).json()
if (/exo/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/exo.json')).json()
if (/femdom/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/femdom.json')).json()
if (/foot/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/foot.json')).json()
if (/freefire/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/freefire.json')).json()
if (/gamewallpaper/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/gamewallpaper.json')).json()
if (/gangbang/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/gangbang.json')).json()
if (/gifs/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/gifs.json')).json()
if (/glasses/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/glasses.json')).json()
if (/gremory/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/gremory.json')).json()
if (/hekel/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/hekel.json')).json()
if (/hentai/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/hentai.json')).json()
if (/hestia/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/hestia.json')).json()
if (/hijaber/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/hijaber.json')).json()
if (/hinata/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/hinata.json')).json()
if (/husbu/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/husbu.json')).json()
if (/inori/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/inori.json')).json()
if (/islamic/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/islamic.json')).json()
if (/isuzu/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/isuzu.json')).json()
if (/itachi/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/itachi.json')).json()
if (/itori/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/itori.json')).json()
if (/jahy/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/jahy.json')).json()
if (/jeni/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/jeni.json')).json()
if (/jiso/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/jiso.json')).json()
if (/justina/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/justina.json')).json()
if (/kaga/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kaga.json')).json()
if (/kagura/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kagura.json')).json()
if (/kakasih/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kakasih.json')).json()
if (/kaori/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kaori.json')).json()
if (/kartun/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kartun.json')).json()
if (/katakata/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/katakata.json')).json()
if (/keneki/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/keneki.json')).json()
if (/kotori/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kotori.json')).json()
if (/kpop/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kpop.json')).json()
if (/kucing/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kucing.json')).json()
if (/kurumi/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/kurumi.json')).json()
if (/lisa/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/lisa.json')).json()
if (/loli/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/loli.json')).json()
if (/madara/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/madara.json')).json()
if (/masturbation/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/masturbation.json')).json()
if (/megumin/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/megumin.json')).json()
if (/mikasa/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/mikasa.json')).json()
if (/mikey/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/mikey.json')).json()
if (/miku/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/miku.json')).json()
if (/milf/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/milf.json')).json()
if (/minato/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/minato.json')).json()
if (/mobil/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/mobil.json')).json()
if (/motor/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/motor.json')).json()
if (/mountain/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/mountain.json')).json()
if (/naruto/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/naruto.json')).json()
if (/neko/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/neko.json')).json()
if (/neko2/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/neko2.json')).json()
if (/nekonime/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/nekonime.json')).json()
if (/nezuko/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/nezuko.json')).json()
if (/onepiece/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/onepiece.json')).json()
if (/orgy/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/orgy.json')).json()
if (/panties/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/panties.json')).json()
if (/pentol/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/pentol.json')).json()
if (/pokemon/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/pokemon.json')).json()
if (/profil/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/profil.json')).json()
if (/progamming/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/programming.json')).json()
if (/pubg/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/pubg.json')).json()
if (/pussy/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/pussy.json')).json()
if (/randblackpink/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/randblackpink.json')).json()
if (/randomnime/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/randomnime.json')).json()
if (/randomnime2/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/randomnime2.json')).json()
if (/rize/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/rize.json')).json()
if (/rose/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/rose.json')).json()
if (/ryujin/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/ryujin.json')).json()
if (/sagiri/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/sagiri.json')).json()
if (/sakura/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/sakura.json')).json()
if (/sasuke/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/sasuke.json')).json()
if (/satanic/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/satanic.json')).json()
if (/shina/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/shina.json')).json()
if (/shinka/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/shinka.json')).json()
if (/shinomiya/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/shinomiya.json')).json()
if (/shizuka/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/shizuka.json')).json()
if (/shota/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/shota.json')).json()
if (/tatasurya/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/tatasurya.json')).json()
if (/technology/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/technology.json')).json()
if (/tejina/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/tejina.json')).json()
if (/tentacles/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/tentacles.json')).json()
if (/thighs/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/thighs.json')).json()
if (/toukachan/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/toukachan.json')).json()
if (/tsunade/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/tsunade.json')).json()
if (/waifu/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/waifu.json')).json()
if (/wallhp/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/wallhp.json')).json()
if (/wallml/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/wallml.json')).json()
if (/wallmlnime/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/wallnime.json')).json()
if (/yotsuba/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/yotsuba.json')).json()
if (/yuki/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/yuki.json')).json()
if (/yulibocil/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/yulibocil.json')).json()
if (/yumeko/.test(command)) link = await (await fetch('https://raw.githubusercontent.com/KirBotz/nyenyee/master/yumeko.json')).json()
let img = link[Math.floor(Math.random() * link.length)];
conn.sendMessage(m.chat, { image: { url: img }, caption: `${command}` }, { quoted: m })
      break;
    }
  }
};
handler.tags = ['randomfoto']
handler.help = handler.command = [
'aesthetic',
'ahegao',
'akira', 
 'akiyama', 'ana', 'anjing', 'art', 'ass', 'asuna', 'ayuzawa', 'bdsm', 'boneka', 'boruto', 'bts', 'cecan', 'chiho', 'chitoge', 'cogan', 'cosplay', 'cosplayloli', 'cosplaysagiri', 'cuckold', 'cum', 'cyber', 'darkjokes', 'deidara', 'doraemon', 'eba', 'elaina', 'emilia', 'ero', 'erza', 'exo', 'femdom', 'foot', 'freefire', 'gamewallpaper', 'gangbang', 'gifs', 'glasses', 'gremory', 'hekel', 'hestia', 'hijaber', 'hinata', 'husbu', 'inori', 'islamic', 'isuzu', 'itachi', 'itori', 'jahy', 'jeni', 'jiso', 'justina', 'kaga', 'kagura', 'kakasih', 'kaori', 'kartun', 'katakata', 'keneki', 'kotori', 'kpop', 'kucing', 'kurumi', 'lisa', 'loli', 'madara', 'masturbation', 'megumin', 'mikasa', 'mikey', 'miku', 'milf', 'minato', 'mobil', 'motor', 'mountain', 'naruto', 'neko', 'neko2', 'nekonime', 'nezuko', 'onepiece', 'orgy', 'panties', 'pentol', 'pokemon', 'profil', 'programming', 'pubg', 'pussy', 'randblackpink', 'randomnime', 'randomnime2', 'rize', 'rose', 'ryujin', 'sagiri', 'sakura', 'sasuke', 'satanic', 'shina', 'shinka', 'shinomiya', 'shizuka', 'shota', 'tatasurya', 'technology', 'tejina', 'tentacles', 'thighs', 'toukachan', 'tsunade', 'waifu', 'wallhp', 'wallml', 'wallnime', 'yotsuba', 'yuki','yulibocil', 'yumeko']
handler.limit = true
module.exports = handler